### ISSUE TITLE
Some questions about evaluation

### ISSUE THREAD

**Issue by scut-xz** [Arvid-pku/ATOKE#4]
Thank you for the great work you’ve done.
I would like to ask about the evaluation process. For both current and historical evaluations, there are six corresponding prompts. For example, in the evaluation of current knowledge, the evaluation includes completion, questions, and paraphrase_completion, which should all correspond to CRS. During evaluation, do you count the CRS+1 for the sample if any of these three are correct, or do you calculate it based on the proportion of correct responses? Another question is, how do you determine whether an answer is correct? Does it only count as correct if the generated word matches the answer exactly?
I am very much looking forward to your response.

**Comment by Arvid-pku** [comment]
Thank you for your interest in our work.

To address your first question: For CES, we tested `completions` rather than `questions`. This is because completion-based testing is more suitable for Rome-type methods. We generated question-type tests to facilitate future work requirements. As for `paraphrase_completion`, its results are reflected in the CES-P.

Regarding your second question: We employed exact string matching, but before matching, we removed case sensitivity and punctuation. We acknowledge that there is room for improvement in the evaluation approach.

**Comment by scut-xz** [comment]
What about the CRS, HRS and HES? "completion" or "paraphrase_completion"?

**Comment by Arvid-pku** [comment]
`paraphrase_completion` is for `xxx-P`, `completion` is for `xxx`

**Comment by scut-xz** [comment]
I would like to ask if you use “prompt” or “time_prompt” for editing?
Additionally, regarding the evaluation, is it based on whether the generated recent words are the answer, or whether the generated words contain the answer? For precise matching, should “new_answer_alias” be used?
Thank you very much for your patience and assistance.

**Comment by Arvid-pku** [comment]
1. `time_prompt`
2. check if the output contains the answer (for example, generating 10 words and checking them)
3. if new_answer_alias exists, then use it.

**Comment by scut-xz** [comment]
Thanks you very much!
